### ISSUE TITLE
Missing annotations cause loud warnings to be logged in Westeros tutorial(s)

### ISSUE THREAD

**Issue by ClaraLuisa** [iiasa/message_ix#383] opened 2020-08-13 08:41 UTC
![image](https://user-images.githubusercontent.com/16190366/90113330-7a2bc600-dd51-11ea-857e-7026912077ac.png)

**Comment by ClaraLuisa** [comment] 2020-08-13 08:50
I think this should be fixed with PR #384.

**Comment by khaeru** [comment] 2020-08-13 11:49
This is a logged warning, not a fatal error. The function/cell has run successfully, and you should find that subsequent cells can still be run.

On every check, we test that the tutorials can all be run top-to-bottom. See https://github.com/iiasa/message_ix/blob/master/message_ix/tests/test_tutorials.py and e.g. [this job](https://github.com/iiasa/message_ix/runs/980009409#step:16:110):
```
message_ix/tests/test_tutorials.py::test_tutorial[westeros_baseline] PASSED
```

So, the tutorial *is* in fact working. That said, I do agree this log message is annoying, and your experience shows that the way Jupyter displays these warning messages can make users think that it is not working. I'll change the title to reflect the issue.

As for the response:

There is not (and has never been) any way to retrieve these annotations from the database through the Python API; same applies to commit messages and comments. Since they can't be retrieved, the code (both ixmp and message_ix) should not be fussy when the user does not set them.

In my view, two possible responses:
1. The log message should be demoted from the "warning" to the "info" level. This will change how it is displayed (if at all) in the Jupyter Notebook. This change is in ixmp, not message_ix: https://github.com/iiasa/ixmp/blob/ac7e75e7316ebd7deb4aa69966d32665e277e9c4/ixmp/core.py#L434-L446
2. The tutorials could be changed, as you do in #384. However, I'm still not sure about this. The point of the tutorials is to teach good modeling practice/usage of message_ix. Storing unretrievable annotations doesn't help to do good modeling. If we explain that the annotation is recorded, but can not be retrieved, I think that only serves to confuse and to impede learning.
3. ixmp and message_ix could be enhanced to allow retrieval of these messages. However, given the current messy state of new metadata and documentation features being added to ixmp, I'm loath to throw this additional change into the mix.

For now, I will address (1) for you through a new PR. Then we can revisit and evaluate whether (2) / #384 is necessary.

**Comment by ClaraLuisa** [comment] 2020-08-13 12:00
@khaeru thanks for clarification. I am sorry for raising this issue, I should have seen that this is jsut a warning.

**Comment by khaeru** [comment] 2020-08-13 12:04
> I am sorry for raising this issue, I should have seen that this is jsut a warning.

Nothing to be sorry for—it's quite valuable to have concrete feedback, so thank you! In this case we learned that the log message/warning looks like an error and is distracting/misleading, something we need to take action to fix.

**Comment by khaeru** [comment] 2020-08-13 12:27
>  I now fail at adding the horizon unsing add_horizon (however adding the set technology also does not work -> see adttached picture).

- @OFR-IIASA reported an issue with `add_horizon()` this morning that occurs on Python versions less than 3.8. If yours happens to be the same, I am currently working on it over at iiasa/ixmp#359 and #381.
- `TypeError: No matching overloads` was addressed in iiasa/ixmp#351 by @zikolach. That is on `master`, but not yet released (we expect to publish 3.1 releases around the beginning of September).

  I apologize that we did not do a good job of documenting this; I just tried to search through GitHub for the error message and found no results. I left https://github.com/iiasa/ixmp/pull/351#issuecomment-673441038 to make it easier for others to discover.

**Comment by ClaraLuisa** [comment] 2020-08-13 12:37
Thanks for the promt response @khaeru! I am working with Python 3.8.3 and was surprised by these errors myself. So by your linked issues I assume that there must be an issue with jpype. Would you agree and do you have any experience on which version of jpype is most stable?

**Comment by khaeru** [comment] 2020-08-13 12:54
> So by your linked issues I assume that there must be an issue with jpype. Would you agree and do you have any experience on which version of jpype is most stable?

Correct—to restate:
- ixmp 3.0.0 was released when JPype1 0.7.5 was the latest version. These two are a working combination.
- ixmp 3.0.0 does not work with the more recent JPype1 1.x series.
- ixmp `master` now works with JPype1 1.x, and so will ixmp 3.1 once it is released.

Each of these is "stable" on its own, it's just that there are mutual incompatibilities.

We do our best to quickly adjust to changes in dependencies like JPype. As much as I wish otherwise, it remains beyond our capacity to make releases every time this happens.

**Comment by ClaraLuisa** [comment] 2020-08-13 13:58
Thanks for the clarification @khaeru ! 

 Unfortunately my understanding of things does not reach deep enough to make use of this explanation. Today I installed message-ix via conda forge  into a otherwise clean _python_ 3.8.3 conda environment. 

This resulted in the following setup: 

- _message-ix_ 3.0.1, 
- _ixmp_ 3.0.0, 
- _jpype_ 1.0.1. 

As this lead to the error discussed above, I now downgraded _jpype1_ to 0.7.5 and now I en up not being able to import _ixmp_ at all (see attachment). 
![image](https://user-images.githubusercontent.com/16190366/90143330-c987eb80-dd7d-11ea-88ef-84259142540d.png)

I am so sorry to be bugging you with this as this the millionst time I am installing/updating message-ix on a computer and should be far more proficient/independent by now. However, I am pretty lost. Do you have an idea on what I did wrong?

**Comment by khaeru** [comment] 2020-08-13 14:05
We have seen issues due to JPype versions being changed (upgraded or downgraded) without a complete uninstall. What I would suggest:
- Create a clean environment.
- Install JPype version 0.7.5 directly, by specifying the version.
- Then, install message-ix.

The last step will require ixmp and thus JPype, but the existing version should satisfy the requirement, so conda should not upgrade it to 1.0.1. After this, you will have JPype 0.7.5, but without any vestigial files from 1.0.1 that might be the cause of the error in your latest screenshot.

**Comment by ClaraLuisa** [comment] 2020-08-13 14:26
Thanks @khaeru for your suggestions. I tried this, thus 

- `conda remove -n message --all` & delete ..\env\message folder
- `conda create -n message` -> create a conda python 3.8 environment
- `conda install -c conda-forge jpype1=0.7.5` - > install JPype
- `conda install -c conda-forge message-ix` -> install message-ix  leaves me with message-ix 3.0.1, ixmp 3.0.0, JPype1 0.7.5

--> this however results in the same error as before: 
![image](https://user-images.githubusercontent.com/16190366/90146770-becf5580-dd81-11ea-985f-169deac0d048.png)

Would you have any other ideas?

**Comment by khaeru** [comment] 2020-08-13 14:46
Does the `activate` step maybe come after `conda create`?

**Comment by ClaraLuisa** [comment] 2020-08-13 15:10
oh yes, very much so!

**Comment by ClaraLuisa** [comment] 2020-08-14 09:35
@khaeru would it maybe be possible to share an exported environment file of a working current message-ix installation?

**Comment by khaeru** [comment] 2020-08-14 09:45
I do not use either Windows or Anaconda, so I can't do that myself. I've asked @iiasa/messageix-developers (here and via Slack) if anyone is able to provide further 1-on-1 tech support.

Since the `TypeError: can't apply this __setattr__ to _jpype._JClass object` is separate from the topic of this issue ("Missing annotations cause loud warnings to be logged in Westeros tutorial(s)"), let's please deal with it in a distinct issue. Then we can discuss and record the fix for that, which will be unrelated to the fix for this issue.

**Comment by francescolovat** [comment] 2020-08-14 10:06
Hi @ClaraLuisa. I am also using `Python 3.8.3` in **Windows** and I successfully created a new `conda env` and managed to run the tutorials. 

Please, let's switch this conversation to Slack until we find a correct set of commands that work in your PC and then we'll leave a final summary comment in this issue before closing it.

**Closed** 2020-08-26 08:39 UTC
Labels: docs
