### ISSUE TITLE
User specific CPLEX solver options via config file

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#262] opened 2019-11-15 14:11 UTC
Currently, cplex solver options can be set either of three ways:
1. https://message.iiasa.ac.at/en/latest/api.html#module-message_ix.models
   from message_ix.models import DEFAULT_CPLEX_OPTIONS
   DEFAULT_CPLEX_OPTIONS['lpmethod'] = whatever
2. s = message_ix.Scenario(...)
   s.solve(solve_options={'lpmethod': whatever})

But because both of these need to be called either everytime when loading message_ix or when calling the solve command, the only other way to permanently change the solver options is in the source code directly (option 3). Therefore, it should be possible to provide user specific configurations via a config file.

**Comment by khaeru** [comment] 2022-04-28 16:42
Closed by #557.

**Closed by khaeru** 2022-04-28 16:42 UTC
Labels: enh

**Comment by khaeru** [comment] 2022-04-28 16:45
This was also a duplicate of #216, I think.
