### ISSUE TITLE
Enable tutorials to be built on RTD

### ISSUE THREAD

**Issue by gidden** [iiasa/message_ix#155] opened 2019-01-25 14:22 UTC
This will require a few concrete steps:

- [ ] move tutorials to doc folder
- [ ] render tutorials when building docs with their own dedicated page, a la pyam
- [ ] make a new install target which installs gams
- [ ] remove explicit gams install on CI and use this target
- [ ] confirm everything works as expected on RTD

My one concern is how our CI examines its OS state (through `$TRAVIS_OS_NAME`. But perhaps we can make this new install target only available on linux to reduce headaches.

@khaeru anything else I'm missing?

**Comment by gidden** [comment] 2019-01-25 14:38
OK, great. Then I would suggest we make a `rtd_env.sh` to set things appropriately and split out `install_travis.sh` into `install_gams.sh` and `install_conda.sh` and have the rtd install target make the appropriate calls.

Only possible issue I can think of is that we need update the PATH variable to know where gams is. I hope that's not a problem..

**Comment by khaeru** [comment] 2019-01-25 14:45
Some references for whenever this is tackled:

- https://jichu4n.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy/
- https://stackoverflow.com/q/14441955

**Comment by LauWien** [comment] 2021-06-25 12:16
Since the closed issue [#156](https://github.com/iiasa/message_ix/issues/156) is marked as a duplicate of this one, and merging PR [#154](https://github.com/iiasa/message_ix/pull/154) should've also closed this one as marked, I propose to close it.

**Closed by LauWien** 2021-06-25 12:16 UTC
Labels: docs, enh
