### ISSUE TITLE
Address failing nightly workflow 

### ISSUE THREAD

**Issue by LauWien** [iiasa/message_ix#591] opened 2022-04-27 15:06 UTC
As first mentioned by @khaeru in the #message_general slack channel, the nightly workflow is failing possible after merging #561, please see [here](https://github.com/iiasa/message_ix/runs/6188543164?check_suite_focus=true#step:9:20).
Please find further information under the thread in #message_general [here](https://iiasa-ece.slack.com/archives/CD0GBHHA4/p1651055949497499).

Taking the liberty to copy @behnam-zakeri tip to check weather the failing nightly is related to the merged PR:

> Before this PR, if there was `capacity_factor` of zero in the input data, the formulation would convert it to 1, because GAMS couldn't understand if this is a zero or a missing value. Our GAMS formulation makes missing `capacity_factor` values equal to 1, and still does that. But after this PR, zero values are not considered missing values, and should remain zero. What we can check is that if there is any input `capacity_factor` equal to zero in this scenario or not. This can be checked like:
>```
>df = sc.par("capacity_factor")
>assert df.loc[df["value"] == 0].empty
>```

**Comment by behnam-zakeri** [comment] 2022-04-27 16:01
I tested this on one of our recent ENGAGE scenarios (`ixmp_dev\ENGAGE_SSP2_v4.1.7\baseline`) and found interesting results. I ran the scenario (A) without the changes introduced in https://github.com/iiasa/message_ix/pull/561 and (B) once after those changes.
1. The objective value, which was the cause of the error in nightly tests, remains almost the same between A and B scenarios (3095978 versus 3095977, respectively).
2. There are indeed differences, as expected, in the parameter `capacity_factor` calculated in GAMS. So, these may be the cause of nightly tests not passing. These changes are as expected those technologies with `capacity_factor=0` in the input file, which will remain the same value in the new formulation, while they were converted to 1 in the old formulation. New formulation is correct here.
3. Another observation, which is not related to this issue, is that the GAMS formulation in both cases omits some technologies from the final calculated `capacity_factor`, which do have `capacity_factor` defined by the user. Examples are "csp_sm1_ppl/AFR". These technologies do not have `input`, `output` and `relation_activity`, and that's why they are not in the set `map_tec_time`, and get omitted from `capacity_factor` in this equation. I believe this is a bug and needs a separate issue, as these technologies at the moment don't appear in capacity equations. I will open the issue.
4. We need to check and perhaps the nightly scenarios. But this PR https://github.com/iiasa/message_ix/pull/561 is doing the right thing for what it was designed.

**Comment by LauWien** [comment] 2022-04-27 16:17
Thank you for checking @behnam-zakeri! 
As for 1. and 2., if I understand correctly, we can update the objective accordingly, since it is expected behavior and we will tackle 3. in a different issue / PR?

**Comment by khaeru** [comment] 2022-04-28 07:02
One point of information: the nightly scenarios were exported some time ago (would need to check to see precisely when). So in a way, loading them and running them is a check that _newer_ versions of message_ix can handle scenarios created with _older_ versions of the code: both loading & running without error and producing numerically identical output.

This requirement is not actually super well defined, e.g. I wouldn't expect scenarios created with versions as old as message_ix v1.x or even 2.x to pass (since we have fixed several bugs in the GAMS code since those). So this is also an opportunity to consider more carefully what precisely we expect and maybe adjust the tests to reflect that.

**Comment by khaeru** [comment] 2022-04-28 07:06
Per Behnam's point (1), this tells us there is something specific about the particular scenario we use for the nightly tests that makes its objective value sensitive to this recent change. This characteristic is **not** in the other, ENGAGE scenario.

It would be nice to try to identify what this is, so we could warn users: “if your scenarios have such-and-such characteristics, outputs may change” etc. However I also realize that might take quite some detective work that we may not have bandwidth for.

**Comment by behnam-zakeri** [comment] 2022-04-28 09:44
Thanks Paul. Good points. I agree that we should test some old scenarios for backward compatibility. Unless we change the code or resolve a bug as this PR does. Then we can update the old check values if the scenario itself is still valid. Especially in this case, as the change of the objective function is significant, I agree that a more detailed investigation can be useful.

**Comment by OFR-IIASA** [comment] 2022-05-10 06:07
As for point 3, the `map_tec_time` may need to be extended to also include `relation_new_capacity` and `relation_total_capacity`. This is where we see entries for the technology "csp_sm1_ppl".

**Comment by gidden** [comment] 2022-05-10 13:47
I opened #603 as one suggestion of how to deal with these issues in the future. To discuss at our message meeting.

**Comment by LauWien** [comment] 2022-05-10 14:52
> I opened #603 as one suggestion of how to deal with these issues in the future. To discuss at our message meeting.

Thank you for this :)
If this PR is still to be discussed / WIP, please could you convert it to a draft and remove me as a reviewer or should I approve this PR to see if the on-approve workflow runs?

**Comment by gidden** [comment] 2022-05-10 15:39
> should I approve this PR to see if the on-approve workflow runs?

That was my thinking, I should have said so explicitly, sorry!

**Comment by LauWien** [comment] 2022-05-10 15:56
It looks like it works ([Link](https://github.com/iiasa/message_ix/runs/6373449410?check_suite_focus=true)).

**Comment by OFR-IIASA** [comment] 2022-05-25 10:31
@khearu and @behnam-zakeri I have noticed that we may have the same issue here as already highlighted in [an earlier PR](https://github.com/iiasa/message_ix/pull/514). The issue is that `enforce()` in `models.py` is only called when the solving with `solve(model="MESSAGE")`, it seems to be missing [here](https://github.com/iiasa/message_ix/blob/9566826be354d39e2b9693d4bba3351aeac73369/message_ix/models.py#L455).

**Comment by khaeru** [comment] 2022-05-25 10:48
Good catch. We need to be careful with inheritance of those classes (i.e. the MESSAGE_MACRO Python class needs to do MESSAGE things and MACRO things), and I think this slipped through.

If you copy MESSAGE.enforce to MACRO.enforce (this will not be the solution, only a check) does that help?

**Comment by OFR-IIASA** [comment] 2022-05-25 11:00
yes this solves the issue. In the gdx file, `is_capacity_factor` is now populated.

**Comment by OFR-IIASA** [comment] 2022-05-25 12:23
I have added the quickfix to a test [PR](https://github.com/iiasa/message_ix/pull/612) and the nightly tests have also passed

**Comment by OFR-IIASA** [comment] 2022-05-25 12:41
Upon resolving this issue, I would suggest to make a new mini-release v3.5.1?

**Comment by khaeru** [comment] 2022-05-25 14:12
> Upon resolving this issue, I would suggest to make a new mini-release v3.5.1?

Agreed we should release quickly to fix the bug.

Ordinarily this would be v3.5.1, yes, but a release will include the changes from #572 that are now on `main`. That marked some deprecations and—as mentioned at https://github.com/iiasa/message_ix/pull/572#issuecomment-1130400005—the [Semantic Versioning specification #7](https://semver.org/#spec-item-7) says “[Minor version Y (x.Y.z)] MUST be incremented if any public API functionality is marked as deprecated.”

Following this logic, the next release will be v3.6.0.

**Closed** 2022-05-25 16:39 UTC
Labels: ci
