### ISSUE TITLE
pip install not working if numerous gdx files already in message_ix folder

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#214] opened 2019-06-26 05:59 UTC
an alternative to `python setup.py install` should be `pip install .'.  This results in a very long loading period where it seems that the necessary dependencies are being identified.  Once complete, the installation process fails due to all files in the local message_ix repository folder being copied into a temporary directory (e.g. C:\Temp).  When there are numerous gdx files already in the message_ix folder, this results in errors where insufficient space is available to copy all the files to the temporary directory.

**Comment by khaeru** [comment] 2019-06-26 08:24
Closing as a duplicate of #141.

**Closed by khaeru** 2019-06-26 08:24 UTC
Labels: bug
